FROM --platform=_PLATFORM_ _FROM-IMAGE0_
USER root

EXPOSE _EXPOSE_

WORKDIR _WORK-DIR-IN-CONTAINER_

COPY ./dist/ _WORK-DIR-IN-CONTAINER__PUBLIC-PATH_/
COPY ./default.conf /etc/nginx/conf.d/default.conf

