FROM --platform=_PLATFORM_ _FROM-IMAGE0_ AS base

# Install dependencies only when needed
FROM base AS deps

RUN apk add --no-cache libc6-compat
WORKDIR _WORK-DIR-IN-CONTAINER_

COPY .env* *.ts *.mjs *.json ./
RUN corepack enable npm && npm i -f


FROM base AS builder

RUN mkdir -p _WORK-DIR-IN-CONTAINER_/node_modules _WORK-DIR-IN-CONTAINER_/app _WORK-DIR-IN-CONTAINER_/public
WORKDIR _WORK-DIR-IN-CONTAINER_

COPY --from=deps _WORK-DIR-IN-CONTAINER_/node_modules ./node_modules
COPY ./app ./app
COPY ./public ./public
COPY .env* *.ts *.mjs *.json ./

ENV NODE_ENV=production
RUN corepack enable npm && npm run build

# Production image, copy all the files and run next
FROM base AS runner

ENV HOSTNAME="0.0.0.0"
ENV PORT=_EXPOSE_

#RUN addgroup --system --gid 1001 nodejs
#RUN adduser --system --uid 1001 nextjs

USER root
#USER nextjs

WORKDIR _APP-DIR-IN-CONTAINER_

COPY --from=builder --chown=nextjs:nodejs _WORK-DIR-IN-CONTAINER_/_DOT-NEXT_/_OUTPUT_/node_modules/ ./node_modules/

EXPOSE _EXPOSE_

#CMD ["ls", ".", "-al", "&&", "node", "server.js"]
ENTRYPOINT ["sh", "-c", "cp -arf _APP-DIR-IN-CONTAINER_/. _WORK-DIR-IN-CONTAINER_/; cd _WORK-DIR-IN-CONTAINER_; node server.js"]
