
FROM --platform=_PLATFORM_ _FROM-IMAGE0_
USER root

ENV TZ=_TZ_
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV JVM_OPTS=_JVM-OPTS_
ENV JAVA_OPTS=_JAVA-OPTS_
ENV LANG=C.UTF-8

EXPOSE _EXPOSE_

ENTRYPOINT ["sh", "-c", "cd _WORK-DIR-IN-CONTAINER_;java $JVM_OPTS $JAVA_OPTS org.springframework.boot.loader.launch.JarLauncher"]

