FROM maven:4.0.0-rc-5-eclipse-temurin-21-noble
user root

LABEL org.opencontainers.image.authors="wuyi <11372349@qq.com>"

# 设置环境变量，避免安装过程中的交互式提示
ENV DEBIAN_FRONTEND=noninteractive \
    WYDEVOPS_WORK_MODE=local \
    WYDEVOPS_LOG_LANGUAGE=en \
    WYDEVOPS_HOME=/root/.wydevops \
    TARGET_PROJECT_HOME=/root/project \
    DOCKER_REPO_CONFIG="" \
    CHART_REPO_CONFIG="" \
    IMAGE_LOCAL_CACHE_DIR=/root/cachedImages \
    ENABLE_CLEAR_CACHED_PARAMS=true \
    ENABLE_DEBUG=false \
    ENABLE_NOTIFY=true \
    ENABLE_FORCE_COVERAGE=true \
    ENABLE_REMOVE_IMAGE=true \
    SHOW_HELP=false \
    SHOW_VERSION=false

COPY ../script $WYDEVOPS_HOME/wydevops/script
COPY ./client-config.yaml $WYDEVOPS_HOME/client-config.yaml

# 给脚本添加可执行权限
RUN chmod +x $WYDEVOPS_HOME/wydevops/script/wydevops-run.sh

# 设置入口点和默认命令
ENTRYPOINT ["/bin/sh","-c","$WYDEVOPS_HOME/wydevops/script/wydevops-run.sh"]
CMD ["-A","linux/amd64","-O","linux/amd64","-B","single","-S","build,docker,chart,package,deploy"]