FROM --platform=_PLATFORM_ _FROM-IMAGE0_ AS base

# Install dependencies only when needed
FROM base AS deps

RUN apk add --no-cache libc6-compat
WORKDIR _WORK-DIR-IN-CONTAINER_

COPY pnpm-lock.yaml *.js *.json ./
RUN corepack enable pnpm && pnpm i --frozen-lockfile

FROM base AS builder

WORKDIR _WORK-DIR-IN-CONTAINER_

COPY --from=deps _WORK-DIR-IN-CONTAINER_/node_modules ./node_modules
COPY ./src ./src
COPY ./public ./public
COPY pnpm-lock.yaml *.js *.json ./

RUN corepack enable pnpm && pnpm run build

# 使用一个包含 shell 的轻量级基础镜像 (alpine)，默认的执行用户为root
FROM --platform=_PLATFORM_ alpine:latest
#USER root

RUN mkdir -p _APP-DIR-IN-CONTAINER__PUBLIC-PATH_
WORKDIR _APP-DIR-IN-CONTAINER_

COPY --from=builder _WORK-DIR-IN-CONTAINER_/dist/ _APP-DIR-IN-CONTAINER__PUBLIC-PATH_/

ENTRYPOINT ["sh", "-c", "cp -arf _APP-DIR-IN-CONTAINER_/. _WORK-DIR-IN-CONTAINER_/" ]
