apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  labels:
    pv: docker-registry-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  hostPath:
    path: /data/docker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: docker-registry
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: local-storage

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: docker-registry
  name: docker-registry-configmap
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
        environment: production
    storage:
      delete:
        enabled: true
      #cache:
      #  blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry      
      tag:
        concurrencylimit: 5
    http:
      addr: :5000
      debug:
        addr: :5001
        prometheus:
          enabled: true
          path: /metrics
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: docker-registry
          image: registry:3.0.0-rc.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: web
              protocol: TCP
          resources:
            requests:
              memory: 500Mi
              cpu: "0.5"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/registry/
              name: docker-registry-data
            - mountPath: /etc/distribution/
              name: docker-registry-config
      volumes:
        - name: docker-registry-data
          persistentVolumeClaim:
            claimName: docker-registry-pvc
        - name: docker-registry-config
          configMap:
            defaultMode: 493
            name: docker-registry-configmap
            optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: docker-registry
spec:
  ports:
    - name: docker-registry-port
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30783
  selector:
    app: docker-registry
  type: NodePort